services:
  - type: web
    name: inequality-web-api
    env: node
    plan: free
    buildCommand: cd ../be_web && npm install
    startCommand: cd ../be_web && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PORT
        value: 10000
    headers:
      - path: "/*"
        headers:
          - key: "Access-Control-Allow-Origin"
            value: "https://inequality-web.vercel.app"
          - key: "Access-Control-Allow-Methods"
            value: "GET,HEAD,PUT,PATCH,POST,DELETE,OPTIONS"
          - key: "Access-Control-Allow-Headers"
            value: "Content-Type,Authorization,Accept"
          - key: "Access-Control-Allow-Credentials"
            value: "true"
